package edu.auburn.mvc.view;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import com.intellij.uiDesigner.core.*;

public class StoreManagerView extends JFrame {

    // Members variables to be shared in the Controller scope.
    public JButton btnCancel;
    public JButton btnAdd;
    public JPanel productPanel;
    public JPanel panelMain;
    public JTextField productIdText;
    public JPanel productIdPanel;
    public JTextField nameText;
    public JPanel namePanel;
    public JLabel priceLabel;
    public JLabel quantityLabel;
    public JTextField priceText;
    public JTextField quantityText;
    public JPanel customerPanel;
    public JPanel purchasePanel;
    public JTextField purchaseIdText;
    public JTextField purchaseProductIdText;
    public JTextField purchaseCustomerIdText;
    public JTextField purchaseQuantityText;
    public JTextField customerIdText;
    public JTextField customerNameText;
    public JTextField zipCodeText;
    public JTextField phoneText;
    public JPanel customerIdPanel;
    public JPanel customerNamePanel;
    public JPanel zipCodePanel;
    public JPanel phonePanel;
    public JPanel purchaseIdPanel;
    public JPanel purchaseProductIdPanel;
    public JPanel purchaseCustomerIdPanel;
    public JPanel purchaseQuantityPanel;
    public JButton addCustomerButton;
    public JButton addPurchaseButton;

    public StoreManagerView() {
        this.setTitle("Store Manager");
        this.setSize(900, 400);
        panelMain = new JPanel();
        panelMain.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        productPanel = new JPanel();
        productPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(productPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        productPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Product Panel", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, getFont(null, Font.BOLD, -1, productPanel.getFont())));
        productIdPanel = new JPanel();
        productIdPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        productPanel.add(productIdPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(2);
        label1.setText("Product ID:");
        productIdPanel.add(label1);
        productIdText = new JTextField();
        productIdText.setColumns(10);
        productIdText.setHorizontalAlignment(2);
        productIdPanel.add(productIdText);
        namePanel = new JPanel();
        namePanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        productPanel.add(namePanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(2);
        label2.setText("Name:");
        namePanel.add(label2);
        nameText = new JTextField();
        nameText.setColumns(10);
        nameText.setHorizontalAlignment(2);
        namePanel.add(nameText);
        btnAdd = new JButton();
        btnAdd.setText("Add Product");
        productPanel.add(btnAdd, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        productPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        priceLabel = new JLabel();
        priceLabel.setHorizontalAlignment(2);
        priceLabel.setText("Price:");
        panel1.add(priceLabel);
        priceText = new JTextField();
        priceText.setColumns(10);
        priceText.setHorizontalAlignment(2);
        panel1.add(priceText);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        productPanel.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        quantityLabel = new JLabel();
        quantityLabel.setHorizontalAlignment(2);
        quantityLabel.setText("Quantity:");
        panel2.add(quantityLabel);
        quantityText = new JTextField();
        quantityText.setColumns(10);
        quantityText.setHorizontalAlignment(2);
        panel2.add(quantityText);
        btnCancel = new JButton();
        btnCancel.setText("Exit Store Manager");
        panelMain.add(btnCancel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        customerPanel = new JPanel();
        customerPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(customerPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        customerPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Customer Panel", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, getFont(null, Font.BOLD, -1, customerPanel.getFont())));
        customerIdPanel = new JPanel();
        customerIdPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        customerPanel.add(customerIdPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setHorizontalAlignment(2);
        label3.setText("Customer ID:");
        customerIdPanel.add(label3);
        customerIdText = new JTextField();
        customerIdText.setColumns(10);
        customerIdText.setHorizontalAlignment(2);
        customerIdPanel.add(customerIdText);
        customerNamePanel = new JPanel();
        customerNamePanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        customerPanel.add(customerNamePanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setHorizontalAlignment(2);
        label4.setText("First and Last Names:");
        customerNamePanel.add(label4);
        customerNameText = new JTextField();
        customerNameText.setColumns(10);
        customerNameText.setHorizontalAlignment(2);
        customerNamePanel.add(customerNameText);
        addCustomerButton = new JButton();
        addCustomerButton.setText("Add Customer");
        customerPanel.add(addCustomerButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zipCodePanel = new JPanel();
        zipCodePanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        customerPanel.add(zipCodePanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setHorizontalAlignment(2);
        label5.setText("Zip Code:");
        zipCodePanel.add(label5);
        zipCodeText = new JTextField();
        zipCodeText.setColumns(10);
        zipCodeText.setHorizontalAlignment(2);
        zipCodePanel.add(zipCodeText);
        phonePanel = new JPanel();
        phonePanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        customerPanel.add(phonePanel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setHorizontalAlignment(2);
        label6.setText("Phone:");
        phonePanel.add(label6);
        phoneText = new JTextField();
        phoneText.setColumns(10);
        phoneText.setHorizontalAlignment(2);
        phonePanel.add(phoneText);
        purchasePanel = new JPanel();
        purchasePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(purchasePanel, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        purchasePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Purchase Panel", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, getFont(null, Font.BOLD, -1, purchasePanel.getFont())));
        purchaseIdPanel = new JPanel();
        purchaseIdPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        purchasePanel.add(purchaseIdPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setHorizontalAlignment(2);
        label7.setText("Purchase ID:");
        purchaseIdPanel.add(label7);
        purchaseIdText = new JTextField();
        purchaseIdText.setColumns(10);
        purchaseIdText.setHorizontalAlignment(2);
        purchaseIdPanel.add(purchaseIdText);
        purchaseProductIdPanel = new JPanel();
        purchaseProductIdPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        purchasePanel.add(purchaseProductIdPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setHorizontalAlignment(2);
        label8.setText("Product ID:");
        purchaseProductIdPanel.add(label8);
        purchaseProductIdText = new JTextField();
        purchaseProductIdText.setColumns(10);
        purchaseProductIdText.setHorizontalAlignment(2);
        purchaseProductIdPanel.add(purchaseProductIdText);
        addPurchaseButton = new JButton();
        addPurchaseButton.setText("Add Purchase");
        purchasePanel.add(addPurchaseButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        purchaseCustomerIdPanel = new JPanel();
        purchaseCustomerIdPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        purchasePanel.add(purchaseCustomerIdPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setHorizontalAlignment(2);
        label9.setText("Customer ID:");
        purchaseCustomerIdPanel.add(label9);
        purchaseCustomerIdText = new JTextField();
        purchaseCustomerIdText.setColumns(10);
        purchaseCustomerIdText.setHorizontalAlignment(2);
        purchaseCustomerIdPanel.add(purchaseCustomerIdText);
        purchaseQuantityPanel = new JPanel();
        purchaseQuantityPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        purchasePanel.add(purchaseQuantityPanel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label10 = new JLabel();
        label10.setHorizontalAlignment(2);
        label10.setText("Quantity:");
        purchaseQuantityPanel.add(label10);
        purchaseQuantityText = new JTextField();
        purchaseQuantityText.setColumns(10);
        purchaseQuantityText.setHorizontalAlignment(2);
        purchaseQuantityPanel.add(purchaseQuantityText);
        this.setContentPane(panelMain);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public Font getFont(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }
}
